version: "3.8"

services:
  api-docs:
    image: ${REGISTRY:-sisa.cafe}/api-docs:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12000:80
    environment:
      CLIENT_ID: 'api-docs'
      CLIENT_SECRET: ''
      REALM: ''
      SCOPES: 'aaa bbb ccc ddd'
      DOCS: "[{ url: 'http://113.161.58.33:10200/loan-application-api/swagger/v1/swagger.json', name: 'Loan', version: 2 }]"
